config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get 'dashboard', to: "dashboard#index"

  resources :workshops, shallow: true do
    resources :projects, shallow: true
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.staff?
        can :read, Workshop, user_ids: user.id
        can :read, Project, user_ids: user.id
      else
        can :read, Project, user_ids: user.id
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  has_many :workshops
  has_many :users
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :workshop
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :business
  belongs_to :workshop

  def admin?
    self.role == "admin"
  end

  def staff?
    self.role == "staff"
  end

end

app/models/workshop.rb
class Workshop < ApplicationRecord
  belongs_to :business
  has_many :projects
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    dashboard_path
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  protected

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = exception.message
    redirect_to dashboard_path
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @workshops = current_user.business.workshops
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_workshop, except: [:show, :edit, :update]
  before_action :set_project

  def new
    @project = @workshop.projects.new
  end

  def create
    @project = @workshop.projects.create(project_params)
    redirect_to workshop_path(@workshop)
  end

  def show

  end

  def edit
    session[:redirect_to] = request.referer
  end

  def update
    @project.update(project_params)
    redirect_to session.delete(:redirect_to)
  end

  def destroy
    @project.delete
    redirect_to workshop_path(@workshop)
  end

  private

  def set_workshop
    @workshop = Workshop.find(params[:workshop_id])
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :reference, :due_date)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]

  def create
    build_resource(sign_up_params)

    self.resource.save
    if self.resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        self.resource = resource.get_user
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company_name, :address, :phone])
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def build_resource(hash=nil)
    self.resource = registration_form = RegistrationForm.new(user: User.new, business: Business.new)
    unless hash.nil? || hash.length == 0
      self.resource.validate hash
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_workshop, only: [:show, :destroy, :edit, :update]

  def new
    @workshop = current_user.business.workshops.new
  end

  def create
    staff = User.find_by(email: params[:staff])
    @workshop = current_user.business.workshops.create(workshop_params)
    @workshop.users << staff
    redirect_to dashboard_path
  end

  def show
    @projects = @workshop.projects
  end

  def edit
    session[:redirect_to] = request.referer
  end

  def update
    staff = User.find_by(email: params[:staff])
    @workshop.update(workshop_params)
    @workshop.users << staff
    redirect_to session.delete(:redirect_to)
  end

  def destroy
    @workshop.delete
    redirect_to dashboard_path
  end

  private

    def workshop_params
      params.require(:workshop).permit(:name, :description, :capacity, :status)
    end

    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
  def staffs_array
    User.where.not(role: "admin").pluck(:email)
  end

  def selected_staffs(workshop)
    result = ""
    workshop.users.where.not(role: "admin").pluck(:email).each do |staff|
      next if staff.blank?
      result += "<li>" + staff + "</li>"
    end
    raw(result)
  end
end

app/views/dashboard/index.html.erb
<%= current_user.email %>
<h1>Company dashboard</h1>
<h2>Workshops </h2>
<%= link_to "Add workshop", new_workshop_path, class: "btn btn-primary" %>

<div class="space"> </div>

<div class="row">
  <% @workshops.each do |ws| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= link_to ws.name.to_s, workshop_path(ws) %></h3>
          <p><%= ws.description %></p>
          <p>Status: <%= ws.status %> </p>
          <p>Capacity: <%= ws.capacity %> </p>
          <p><%= link_to 'Delete', workshop_path(ws), class: 'btn btn-danger', method: :delete %></p>
          <p><%= link_to 'Edit', edit_workshop_path(ws), class: 'btn btn-primary' %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/_form.html.erb
<h1>Create a project</h1>
<%= form_for [workshop, project] do |project| %>
  <%= project.label :name %>
  <%= project.text_field :name %>
  <%= project.label :description %>
  <%= project.text_area :description %>
  <%= project.label :reference %>
  <%= project.text_field :reference %>
  <%= project.label :due_date %>
  <%= project.date_field :due_date %>
  <%= project.submit %>
<% end %>

app/views/projects/edit.html.erb
<%= render partial: "form", locals: {project: @project, workshop: @workshop} %>

app/views/projects/new.html.erb
<%= render partial: "form", locals: {project: @project, workshop: @workshop} %>

app/views/projects/show.html.erb
<%= link_to 'Dashboard', dashboard_path, class: 'btn btn-primary' %>
<%= link_to 'Workshop', workshop_path(@project.workshop), class: 'btn btn-primary' %>
<h1><%= @project.name %></h1>
<p><%= @project.description %></p>
<p><%= @project.reference %></p>
<p><%= @project.due_date %></p>
<p><%= link_to 'Delete', project_path(@project, workshop_id: @project.workshop.id), class: 'btn btn-danger', method: :delete %></p>
<p><%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %></p>

app/views/workshops/_form.html.erb
<h1>Create a workshop</h1>
<%= form_for workshop do |ws| %>
  <%= ws.label :name %>
  <%= ws.text_field :name %>
  <%= ws.label :description %>
  <%= ws.text_area :description %>
  <%= ws.label :capacity %>
  <%= ws.number_field :capacity %>
  <%= ws.label :status %>
  <%= ws.select :status, ["Active", "Inactive", "Maintainance"] %>
  <%= label_tag :staff %>
  <%= select_tag :staff, options_for_select(staffs_array) %>
  <%= ws.submit %>
<% end %>

app/views/workshops/edit.html.erb
<%= render partial: "form", locals: {workshop: @workshop} %>

app/views/workshops/new.html.erb
<%= render partial: "form", locals: {workshop: @workshop} %>

app/views/workshops/show.html.erb
<%= link_to 'Dashboard', dashboard_path, class: 'btn btn-primary' %>
<h1><%= @workshop.name %></h1>
<p><%= @workshop.description %></p>
<p><%= @workshop.capacity %></p>
<p><%= @workshop.status %></p>
<p>Staff: <ul><%= selected_staffs(@workshop) %></ul></p>
<p><%= link_to 'Delete', workshop_path(@workshop), class: 'btn btn-danger', method: :delete %></p>
<p><%= link_to 'Edit', edit_workshop_path(@workshop), class: 'btn btn-primary' %></p>

<h2>Projects</h2>
<%= link_to "Add project", new_workshop_project_path(@workshop), class: "btn btn-primary" %>

<div class="space"> </div>

<div class="row">
  <% @projects.each do |project| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= link_to project.name.to_s, project_path(project) %></h3>
          <p><%= project.description %></p>
          <p>Status: <%= project.reference %> </p>
          <p>Capacity: <%= project.due_date %> </p>
          <p><%= link_to 'Delete', project_path(project, workshop_id: @workshop.id), class: 'btn btn-danger', method: :delete %></p>
          <p><%= link_to 'Edit', edit_project_path(project), class: 'btn btn-primary' %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>